version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:4000
      - PROJECT_DATA_SERVICE_URL=http://project-data-service:4001
      - REPORT_SERVICE_URL=http://report-service:4002
      - NOTIFICATION_SERVICE_URL=http://notification-service:4003
      - STORAGE_SERVICE_URL=http://storage-service:4004
      - PLATFORM_INTEGRATIONS_SERVICE_URL=http://platform-integrations-service:4005
    depends_on:
      - auth-service
      - platform-integrations-service
    networks:
      prism-network:
        aliases: 
          - localhost

  # Authentication Service
  auth-service:
    build:
      context: ./backend/services/auth-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/prism-auth
      - JWT_SECRET=your_jwt_secret_key_here
      - TOKEN_EXPIRATION=24h
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_EXCHANGE=prism.events
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy      
    networks:
      - prism-network

  # Platform Integrations Service
  platform-integrations-service:
    build:
      context: ./backend/services/platform-integrations-service
    ports:
      - "4005:4005"
    environment:
      - PORT=4005
      - MONGODB_URI=mongodb://mongo:27017/prism-integrations
      - JWT_SECRET=your_jwt_secret_key_here
      - ENCRYPTION_KEY=your_32_character_encryption_key_here_12345
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - prism-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api-gateway:3000
    networks:
      - prism-network

  # MongoDB
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - prism-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - prism-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Report Generation Service
  report-service:
    build:
      context: ./backend/services/report-generation-service
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=prism-reports
      - JWT_SECRET=your_jwt_secret_key_here
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_EXCHANGE=prism.events
      - STORAGE_DIR=/usr/src/app/storage
    volumes:
      - ./backend/services/report-generation-service:/usr/src/app
      - /usr/src/app/node_modules
      - report-storage:/usr/src/app/storage
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - prism-network

networks:
  prism-network:
    driver: bridge

volumes:
  mongo-data:
  rabbitmq-data:
  report-storage: